name: build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Download go modules
        run: go mod download

      - name: Go build
        run: go build -o /dev/null ./...
