name: releaser

on:
  push:
    tags:
      - '*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config=.github/goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      